backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Slug", name: "slug", widget: "string" }
      - label: "Layout"
        name: "layout"
        widget: "select"
        options: ["post", "link-post"]
        default: "post"
        required: false
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["link", "music"]
        required: false
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Summary", name: "summary", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "notes"
    label: "Notes"
    folder: "_notes"
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Hide Title", name: "hide_title", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
